name: matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [10,6,8]
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - name: Do the GH Action
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v