name: Shell Commands

on: [pull_request]

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: Print our file contents
        run: cat $HOME/secret.json
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello timbo!!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  
  brand-new-windows:
    runs-on: windows-latest
    needs: [ run-shell-command]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
