name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello timbo!!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  
  brand-new-windows:
    runs-on: windows-latest
    needs: [ run-shell-command]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
